server:
  port: 8002

spring:
  application:
    name: webflux-r2dbc

  main:
    allow-bean-definition-overriding: true

  output:
    ansi:
      enabled: always

  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/postgres
    username: postgres
    password: admin123!
    properties:
      lock_timeout: 40000
      statement_timeout: 40000
      idle_in_transaction_session_timeout: 40000
      connectTimeout: PT55S

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

logging:
  level:
    com.roopy: DEBUG