server:
  port: 8001

spring:
  application:
    name: webflux-jdbc

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin123!
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      pool-name: StoreHikariPool

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

logging:
  level:
    com.roopy: debug